version: '3.9'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - pa_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
     - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - pa_network

networks:
  pa_network:
    driver: bridge

volumes:
  local_pgdata:
  pgadmin-data: